title: simply24365's Page
description: This is a test page for GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simply24365.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
